const PrivacyPolicy = () => {
  return (
    <div className="text-[18px] max-w-6xl mx-auto my-10">
      <h1 className="text-4xl font-[800] text-center">Privacy Policy</h1>
      <p>
        We at ratethelandlord.org value your privacy and are committed to
        maintaining the confidentiality of your information. This Privacy Policy
        outlines how we handle data on our website:
      </p>

      <div className="mt-3">
        <h1 className="font-bold">1. Information Collection</h1>
        <p>
          We do not collect any personal information from visitors to our
          website.
        </p>
      </div>
      <div className="mt-3">
        <h1 className="font-bold">2. Cookies and Tracking Technologies</h1>
        <p>
          Our website does not use cookies or any other tracking technologies to
          collect information about visitors other than those employed by our
          Analytics Service, PostHog, reCaptcha, and Google Advertisements
          (outlined below).
        </p>
      </div>
      <div className="mt-3">
        <h1 className="font-bold">3. Information Sharing</h1>
        <p>
          We do not share any information with third parties, as we do not
          collect any information in the first place.
        </p>
      </div>
      <div className="mt-3">
        <h1 className="font-bold">4. Data Security</h1>
        <p>
          While we do not collect any personal information, we still take
          appropriate measures to ensure the security of our website and protect
          against unauthorized access, alteration, disclosure, or destruction.
        </p>
      </div>
      <div className="mt-3">
        <h1 className="font-bold">5. Children&rsquo;s Privacy</h1>
        <p>
          Our website is not directed at children under the age of 13, and we do
          not knowingly collect any personal information from children.
        </p>
      </div>
      <div className="mt-3">
        <h1 className="font-bold">6. Analytic Services</h1>
        <p>
          We use a third-party analytics service, PostHog, to help us understand
          how visitors interact with our website. This service collects
          information such as your IP address, browser type, device information,
          and usage patterns. The information generated by this service is used
          to analyze trends, track user movements on the website, and gather
          demographic information about our user base. This helps us improve our
          website and tailor our content to better meet the needs of our users.
          We use PostHog on our website to collect and analyze data about user
          interactions and behavior. PostHog collects information such as your
          IP address, browser type, device information, and interactions with
          our website. The information collected by PostHog is used to analyze
          trends, track user movements on the website, and gather demographic
          information about our user base. This helps us improve our website and
          tailor our content to better meet the needs of our users. PostHog may
          use cookies or other tracking technologies to collect and store this
          information. By using our website, you consent to the processing of
          data about you by PostHog in the manner and for the purposes set out
          above. Please note that your use of PostHog is subject to
          PostHog&rsquo;s Privacy Policy and Terms of Service, which govern the
          collection and use of data by PostHog in connection with analytics
          services. By using our website, you consent to the processing of data
          about you by PostHog in the manner and for the purposes set out above.
        </p>
      </div>
      <div className="mt-3">
        <h1 className="font-bold">7. Bot Detection Services</h1>
        <p>
          We use Google reCAPTCHA on our website to help protect against
          automated abuse, such as spam and bot traffic. reCAPTCHA collects
          certain information from users in order to determine whether they are
          human or bots, including IP addresses, browser and device information,
          and interaction data. The information collected by reCAPTCHA is used
          solely for bot detection purposes and is not used to personally
          identify individual users. By using our website, you consent to the
          processing of data about you by Google reCAPTCHA in the manner and for
          the purposes set out above. Please note that your use of reCAPTCHA is
          subject to Google&rsquo;s Privacy Policy and Terms of Service, which
          govern the collection and use of data by Google in connection with
          reCAPTCHA.
        </p>
      </div>
      <div className="mt-3">
        <h1 className="font-bold">8. Advertising Services</h1>
        <p>
          We use Google Ads on our website to display advertisements to our
          visitors. Google Ads may use cookies and other tracking technologies
          to collect information about your visits to this and other websites in
          order to provide targeted advertisements about goods and services that
          may be of interest to you. The information collected by Google Ads may
          include your IP address, browser type, device information, and
          interactions with ad content. This information is used to personalize
          the advertisements that are displayed to you and to measure the
          effectiveness of our advertising campaigns. By using our website, you
          consent to the processing of data about you by Google Ads in the
          manner and for the purposes set out above. Please note that your use
          of Google Ads is subject to Google&rsquo;s Privacy Policy and Terms of
          Service, which govern the collection and use of data by Google in
          connection with advertising services.
        </p>
      </div>
      <div className="mt-3">
        <h1 className="font-bold">9. GDPR</h1>
        <p className="my-4 underline">Landlord Names</p>
        <p>
          We allow users to submit content that use or reference the Landlords
          name provided that content is allowed within our Moderation
          Guidelines. Landlord names are allowed provided that they describe the
          individuals behaviour or performance as a Landlord conducting their
          commercial activity in that name. We believe this information is vital
          so that future Tenants can be as informed as possible. We don&rsquo;t
          allow reviews that includes negative comments about identifiable
          individuals outside of this group. We may allow reviews that mentions
          demographic attributes about an identifiable person if we believe the
          review is used to describe a landlord and tenant relationship. General
          discussions of landlord misconduct are allowed, including most
          discussions of illegal activities, discrimination, and sexual
          harassment. The naming of individuals in regards to a corporation
          (such as a Property Management Company) are not allowed. Rate The
          Landlord Inc. does not otherwise collect or process personal
          information. Reviews are considered legitimate expression and
          contributions to the public debate. If the review contains personal
          information as defined by the GDPR it may be edited or removed. If you
          have any questions, please contact us at the email below or report the
          Review for further assessment.
        </p>
      </div>
      <div className="mt-3">
        <h1 className="font-bold">10. DSA</h1>
        <p>
          The landlord review section of this website provides a platform for
          users to share their opinions and experiences related to landlords.
          These reviews are submitted by individual users and do not necessarily
          reflect the views of the website owners or administrators. Accuracy of
          Information: We cannot guarantee the validity of all information
          posted. Users are encouraged to conduct their own research and
          verification before making any decisions based on the information
          provided on this website. Moderation: Reviews may be moderated to
          ensure they comply with our moderation guidelines. We reserve the
          right to remove reviews that are deemed inappropriate, inaccurate, or
          violate our terms of service. Legal Disclaimer: The reviews and
          opinions expressed on this website are solely those of the individual
          users and do not constitute legal or professional advice. We do not
          endorse any specific landlord or property management company mentioned
          in these reviews. Liability: We are not liable for any damages or
          losses incurred as a result of using the information provided on this
          website. Users rely on the reviews at their own risk. Updates: This
          disclaimer may be updated from time to time. Users are advised to
          review it periodically for any changes. By using this website, you
          agree to abide by the terms outlined in this disclaimer.
        </p>
      </div>
      <div className="mt-3">
        <h1 className="font-bold">11. Changes to This Privacy Policy</h1>
        <p>
          We reserve the right to update or change our Privacy Policy at any
          time. Any changes will be effective immediately upon posting the
          updated Privacy Policy on this page.
        </p>
      </div>
      <div className="mt-3">
        <h1 className="font-bold">12. Contact Information</h1>
        <p>
          If you have any questions about Privacy Policy, please contact us at
          contact@ratethelandlord.org.
        </p>
      </div>
    </div>
  );
};

export default PrivacyPolicy;
